[build]
  publish = "."

[[redirects]]
  from = "/about/"
  to = "/about.html"
  status = 200
[[redirects]]
  from = "/how-i-help/"
  to = "/how-i-help.html"
  status = 200
[[redirects]]
  from = "/contact/"
  to = "/contact.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
